// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

use TabGroup;
use ffi;
use glib;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use glib::object::Downcast;
use glib::object::IsA;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use glib::signal::SignalHandlerId;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use std::boxed::Box as Box_;
use std::mem;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct ApplicationWindow(Object<ffi::TeplApplicationWindow, ffi::TeplApplicationWindowClass>): TabGroup;

    match fn {
        get_type => || ffi::tepl_application_window_get_type(),
    }
}

impl ApplicationWindow {
    //#[cfg(any(feature = "v2_0", feature = "dox"))]
    //pub fn get_from_gtk_application_window(gtk_window: /*Ignored*/&gtk::ApplicationWindow) -> Option<ApplicationWindow> {
    //    unsafe { TODO: call ffi::tepl_application_window_get_from_gtk_application_window() }
    //}
}

pub trait ApplicationWindowExt {
    //#[cfg(any(feature = "v2_0", feature = "dox"))]
    //fn get_application_window(&self) -> /*Ignored*/Option<gtk::ApplicationWindow>;

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn set_tab_group<P: IsA<TabGroup>>(&self, tab_group: &P);

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn connect_property_application_window_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<ApplicationWindow> + IsA<glib::object::Object>> ApplicationWindowExt for O {
    //#[cfg(any(feature = "v2_0", feature = "dox"))]
    //fn get_application_window(&self) -> /*Ignored*/Option<gtk::ApplicationWindow> {
    //    unsafe { TODO: call ffi::tepl_application_window_get_application_window() }
    //}

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn set_tab_group<P: IsA<TabGroup>>(&self, tab_group: &P) {
        unsafe {
            ffi::tepl_application_window_set_tab_group(self.to_glib_none().0, tab_group.to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn connect_property_application_window_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::application-window",
                transmute(notify_application_window_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

#[cfg(any(feature = "v2_0", feature = "dox"))]
unsafe extern "C" fn notify_application_window_trampoline<P>(this: *mut ffi::TeplApplicationWindow, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<ApplicationWindow> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&ApplicationWindow::from_glib_borrow(this).downcast_unchecked())
}
