// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

use Buffer;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use Encoding;
use File;
#[cfg(any(feature = "v2_0", feature = "dox"))]
use NewlineType;
use ffi;
use gio;
use glib;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct FileLoader(Object<ffi::TeplFileLoader, ffi::TeplFileLoaderClass>);

    match fn {
        get_type => || ffi::tepl_file_loader_get_type(),
    }
}

impl FileLoader {
    pub fn new(buffer: &Buffer, file: &File) -> FileLoader {
        unsafe {
            from_glib_full(ffi::tepl_file_loader_new(buffer.to_glib_none().0, file.to_glib_none().0))
        }
    }
}

pub trait FileLoaderExt {
    fn get_buffer(&self) -> Option<Buffer>;

    fn get_chunk_size(&self) -> i64;

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn get_encoding(&self) -> Option<Encoding>;

    fn get_file(&self) -> Option<File>;

    fn get_location(&self) -> Option<gio::File>;

    fn get_max_size(&self) -> i64;

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn get_newline_type(&self) -> NewlineType;

    //fn load_async<'a, 'b, 'c, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::FileProgressCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>, S: Into<Option<&'c /*Unimplemented*/glib::DestroyNotify>>, T: FnOnce(Result<(), Error>) + Send + 'static>(&self, io_priority: glib::Priority, cancellable: P, progress_callback: Q, progress_callback_data: R, progress_callback_notify: S, callback: T);

    fn set_chunk_size(&self, chunk_size: i64);

    fn set_max_size(&self, max_size: i64);

    fn connect_property_buffer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_chunk_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_file_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_location_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_max_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<FileLoader> + IsA<glib::object::Object>> FileLoaderExt for O {
    fn get_buffer(&self) -> Option<Buffer> {
        unsafe {
            from_glib_none(ffi::tepl_file_loader_get_buffer(self.to_glib_none().0))
        }
    }

    fn get_chunk_size(&self) -> i64 {
        unsafe {
            ffi::tepl_file_loader_get_chunk_size(self.to_glib_none().0)
        }
    }

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn get_encoding(&self) -> Option<Encoding> {
        unsafe {
            from_glib_none(ffi::tepl_file_loader_get_encoding(self.to_glib_none().0))
        }
    }

    fn get_file(&self) -> Option<File> {
        unsafe {
            from_glib_none(ffi::tepl_file_loader_get_file(self.to_glib_none().0))
        }
    }

    fn get_location(&self) -> Option<gio::File> {
        unsafe {
            from_glib_none(ffi::tepl_file_loader_get_location(self.to_glib_none().0))
        }
    }

    fn get_max_size(&self) -> i64 {
        unsafe {
            ffi::tepl_file_loader_get_max_size(self.to_glib_none().0)
        }
    }

    #[cfg(any(feature = "v2_0", feature = "dox"))]
    fn get_newline_type(&self) -> NewlineType {
        unsafe {
            from_glib(ffi::tepl_file_loader_get_newline_type(self.to_glib_none().0))
        }
    }

    //fn load_async<'a, 'b, 'c, P: Into<Option<&'a /*Ignored*/gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::FileProgressCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>, S: Into<Option<&'c /*Unimplemented*/glib::DestroyNotify>>, T: FnOnce(Result<(), Error>) + Send + 'static>(&self, io_priority: glib::Priority, cancellable: P, progress_callback: Q, progress_callback_data: R, progress_callback_notify: S, callback: T) {
    //    unsafe { TODO: call ffi::tepl_file_loader_load_async() }
    //}

    fn set_chunk_size(&self, chunk_size: i64) {
        unsafe {
            ffi::tepl_file_loader_set_chunk_size(self.to_glib_none().0, chunk_size);
        }
    }

    fn set_max_size(&self, max_size: i64) {
        unsafe {
            ffi::tepl_file_loader_set_max_size(self.to_glib_none().0, max_size);
        }
    }

    fn connect_property_buffer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::buffer",
                transmute(notify_buffer_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_chunk_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::chunk-size",
                transmute(notify_chunk_size_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_file_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::file",
                transmute(notify_file_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_location_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::location",
                transmute(notify_location_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_max_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::max-size",
                transmute(notify_max_size_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn notify_buffer_trampoline<P>(this: *mut ffi::TeplFileLoader, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<FileLoader> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&FileLoader::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_chunk_size_trampoline<P>(this: *mut ffi::TeplFileLoader, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<FileLoader> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&FileLoader::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_file_trampoline<P>(this: *mut ffi::TeplFileLoader, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<FileLoader> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&FileLoader::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_location_trampoline<P>(this: *mut ffi::TeplFileLoader, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<FileLoader> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&FileLoader::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_max_size_trampoline<P>(this: *mut ffi::TeplFileLoader, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<FileLoader> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&FileLoader::from_glib_borrow(this).downcast_unchecked())
}
