// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct GutterRendererFolds(Object<ffi::TeplGutterRendererFolds, ffi::TeplGutterRendererFoldsClass>);

    match fn {
        get_type => || ffi::tepl_gutter_renderer_folds_get_type(),
    }
}

impl GutterRendererFolds {
    //pub fn new() -> GutterRendererFolds {
    //    unsafe { TODO: call ffi::tepl_gutter_renderer_folds_new() }
    //}
}

impl Default for GutterRendererFolds {
    fn default() -> Self {
        Self::new()
    }
}

pub trait GutterRendererFoldsExt {
    //fn set_state(&self, state: /*Ignored*/GutterRendererFoldsState);
}

impl<O: IsA<GutterRendererFolds>> GutterRendererFoldsExt for O {
    //fn set_state(&self, state: /*Ignored*/GutterRendererFoldsState) {
    //    unsafe { TODO: call ffi::tepl_gutter_renderer_folds_set_state() }
    //}
}
