// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

#[cfg(any(feature = "v3_0", feature = "dox"))]
use Tab;
use ffi;
use glib;
#[cfg(any(feature = "v3_0", feature = "dox"))]
use glib::object::Downcast;
use glib::object::IsA;
#[cfg(any(feature = "v3_0", feature = "dox"))]
use glib::signal::SignalHandlerId;
#[cfg(any(feature = "v3_0", feature = "dox"))]
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
#[cfg(any(feature = "v3_0", feature = "dox"))]
use std::boxed::Box as Box_;
use std::mem;
#[cfg(any(feature = "v3_0", feature = "dox"))]
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct TabLabel(Object<ffi::TeplTabLabel, ffi::TeplTabLabelClass>);

    match fn {
        get_type => || ffi::tepl_tab_label_get_type(),
    }
}

impl TabLabel {
    //#[cfg(any(feature = "v3_0", feature = "dox"))]
    //pub fn new(tab: &Tab) -> TabLabel {
    //    unsafe { TODO: call ffi::tepl_tab_label_new() }
    //}
}

pub trait TabLabelExt {
    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn get_tab(&self) -> Option<Tab>;

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn update_tooltip(&self);

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn connect_property_tab_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<TabLabel> + IsA<glib::object::Object>> TabLabelExt for O {
    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn get_tab(&self) -> Option<Tab> {
        unsafe {
            from_glib_none(ffi::tepl_tab_label_get_tab(self.to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn update_tooltip(&self) {
        unsafe {
            ffi::tepl_tab_label_update_tooltip(self.to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v3_0", feature = "dox"))]
    fn connect_property_tab_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::tab",
                transmute(notify_tab_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

#[cfg(any(feature = "v3_0", feature = "dox"))]
unsafe extern "C" fn notify_tab_trampoline<P>(this: *mut ffi::TeplTabLabel, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<TabLabel> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&TabLabel::from_glib_borrow(this).downcast_unchecked())
}
