// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

extern crate tepl_sys;
extern crate shell_words;
extern crate tempdir;
use std::env;
use std::error::Error;
use std::path::Path;
use std::mem::{align_of, size_of};
use std::process::Command;
use std::str;
use tepl_sys::*;

static PACKAGES: &[&str] = &["tepl-3"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Compiler, Box<Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Compiler { args })
    }

    pub fn define<'a, V: Into<Option<&'a str>>>(&mut self, var: &str, val: V) {
        let arg = match val.into() {
            None => format!("-D{}", var), 
            Some(val) => format!("-D{}={}", var, val),
        };
        self.args.push(arg);
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {:?} failed, {}",
                               &cmd, status).into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{} {}", name, err).into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let mut cmd = Command::new("pkg-config");
    cmd.arg("--cflags");
    cmd.args(packages);
    let out = cmd.output()?;
    if !out.status.success() {
        return Err(format!("command {:?} returned {}", 
                           &cmd, out.status).into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}


#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
    /// Number of tests that failed to compile.
    failed_to_compile: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn record_failed_to_compile(&mut self) {
        self.failed += 1;
        self.failed_to_compile += 1;
    }
    fn summary(&self) -> String {
        format!(
            "{} passed; {} failed (compilation errors: {})",
            self.passed,
            self.failed,
            self.failed_to_compile)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let tmpdir = tempdir::TempDir::new("abi").expect("temporary directory");
    let cc = Compiler::new().expect("configured compiler");

    assert_eq!("1",
               get_c_value(tmpdir.path(), &cc, "1").expect("C constant"),
               "failed to obtain correct constant value for 1");

    let mut results : Results = Default::default();
    for (i, &(name, rust_value)) in RUST_CONSTANTS.iter().enumerate() {
        match get_c_value(tmpdir.path(), &cc, name) {
            Err(e) => {
                results.record_failed_to_compile();
                eprintln!("{}", e);
            },
            Ok(ref c_value) => {
                if rust_value == c_value {
                    results.record_passed();
                } else {
                    results.record_failed();
                    eprintln!("Constant value mismatch for {}\nRust: {:?}\nC:    {:?}",
                              name, rust_value, c_value);
                }
            }
        };
        if (i + 1) % 25 == 0 {
            println!("constants ... {}", results.summary());
        }
    }
    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let tmpdir = tempdir::TempDir::new("abi").expect("temporary directory");
    let cc = Compiler::new().expect("configured compiler");

    assert_eq!(Layout {size: 1, alignment: 1},
               get_c_layout(tmpdir.path(), &cc, "char").expect("C layout"),
               "failed to obtain correct layout for char type");

    let mut results : Results = Default::default();
    for (i, &(name, rust_layout)) in RUST_LAYOUTS.iter().enumerate() {
        match get_c_layout(tmpdir.path(), &cc, name) {
            Err(e) => {
                results.record_failed_to_compile();
                eprintln!("{}", e);
            },
            Ok(c_layout) => {
                if rust_layout == c_layout {
                    results.record_passed();
                } else {
                    results.record_failed();
                    eprintln!("Layout mismatch for {}\nRust: {:?}\nC:    {:?}",
                              name, rust_layout, &c_layout);
                }
            }
        };
        if (i + 1) % 25 == 0 {
            println!("layout    ... {}", results.summary());
        }
    }
    results.expect_total_success();
}

fn get_c_layout(dir: &Path, cc: &Compiler, name: &str) -> Result<Layout, Box<Error>> {
    let exe = dir.join("layout");
    let mut cc = cc.clone();
    cc.define("ABI_TYPE_NAME", name);
    cc.compile(Path::new("tests/layout.c"), &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed, {:?}",
                           &abi_cmd, &output).into());
    }

    let stdout = str::from_utf8(&output.stdout)?;
    let mut words = stdout.trim().split_whitespace();
    let size = words.next().unwrap().parse().unwrap();
    let alignment = words.next().unwrap().parse().unwrap();
    Ok(Layout {size, alignment})
}

fn get_c_value(dir: &Path, cc: &Compiler, name: &str) -> Result<String, Box<Error>> {
    let exe = dir.join("constant");
    let mut cc = cc.clone();
    cc.define("ABI_CONSTANT_NAME", name);
    cc.compile(Path::new("tests/constant.c"), &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed, {:?}",
                           &abi_cmd, &output).into());
    }

    Ok(str::from_utf8(&output.stdout)?.trim().to_owned())
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    ("TeplAbstractFactory", Layout {size: size_of::<TeplAbstractFactory>(), alignment: align_of::<TeplAbstractFactory>()}),
    ("TeplAbstractFactoryClass", Layout {size: size_of::<TeplAbstractFactoryClass>(), alignment: align_of::<TeplAbstractFactoryClass>()}),
    ("TeplApplication", Layout {size: size_of::<TeplApplication>(), alignment: align_of::<TeplApplication>()}),
    ("TeplApplicationClass", Layout {size: size_of::<TeplApplicationClass>(), alignment: align_of::<TeplApplicationClass>()}),
    ("TeplApplicationWindow", Layout {size: size_of::<TeplApplicationWindow>(), alignment: align_of::<TeplApplicationWindow>()}),
    ("TeplApplicationWindowClass", Layout {size: size_of::<TeplApplicationWindowClass>(), alignment: align_of::<TeplApplicationWindowClass>()}),
    ("TeplBuffer", Layout {size: size_of::<TeplBuffer>(), alignment: align_of::<TeplBuffer>()}),
    ("TeplBufferClass", Layout {size: size_of::<TeplBufferClass>(), alignment: align_of::<TeplBufferClass>()}),
    ("TeplCompressionType", Layout {size: size_of::<TeplCompressionType>(), alignment: align_of::<TeplCompressionType>()}),
    ("TeplFile", Layout {size: size_of::<TeplFile>(), alignment: align_of::<TeplFile>()}),
    ("TeplFileClass", Layout {size: size_of::<TeplFileClass>(), alignment: align_of::<TeplFileClass>()}),
    ("TeplFileLoader", Layout {size: size_of::<TeplFileLoader>(), alignment: align_of::<TeplFileLoader>()}),
    ("TeplFileLoaderClass", Layout {size: size_of::<TeplFileLoaderClass>(), alignment: align_of::<TeplFileLoaderClass>()}),
    ("TeplFileLoaderError", Layout {size: size_of::<TeplFileLoaderError>(), alignment: align_of::<TeplFileLoaderError>()}),
    ("TeplFileMetadata", Layout {size: size_of::<TeplFileMetadata>(), alignment: align_of::<TeplFileMetadata>()}),
    ("TeplFileMetadataClass", Layout {size: size_of::<TeplFileMetadataClass>(), alignment: align_of::<TeplFileMetadataClass>()}),
    ("TeplFileSaver", Layout {size: size_of::<TeplFileSaver>(), alignment: align_of::<TeplFileSaver>()}),
    ("TeplFileSaverClass", Layout {size: size_of::<TeplFileSaverClass>(), alignment: align_of::<TeplFileSaverClass>()}),
    ("TeplFileSaverError", Layout {size: size_of::<TeplFileSaverError>(), alignment: align_of::<TeplFileSaverError>()}),
    ("TeplFileSaverFlags", Layout {size: size_of::<TeplFileSaverFlags>(), alignment: align_of::<TeplFileSaverFlags>()}),
    ("TeplFoldRegion", Layout {size: size_of::<TeplFoldRegion>(), alignment: align_of::<TeplFoldRegion>()}),
    ("TeplFoldRegionClass", Layout {size: size_of::<TeplFoldRegionClass>(), alignment: align_of::<TeplFoldRegionClass>()}),
    ("TeplGutterRendererFolds", Layout {size: size_of::<TeplGutterRendererFolds>(), alignment: align_of::<TeplGutterRendererFolds>()}),
    ("TeplGutterRendererFoldsClass", Layout {size: size_of::<TeplGutterRendererFoldsClass>(), alignment: align_of::<TeplGutterRendererFoldsClass>()}),
    ("TeplGutterRendererFoldsState", Layout {size: size_of::<TeplGutterRendererFoldsState>(), alignment: align_of::<TeplGutterRendererFoldsState>()}),
    ("TeplInfoBar", Layout {size: size_of::<TeplInfoBar>(), alignment: align_of::<TeplInfoBar>()}),
    ("TeplNewlineType", Layout {size: size_of::<TeplNewlineType>(), alignment: align_of::<TeplNewlineType>()}),
    ("TeplNotebook", Layout {size: size_of::<TeplNotebook>(), alignment: align_of::<TeplNotebook>()}),
    ("TeplSelectionType", Layout {size: size_of::<TeplSelectionType>(), alignment: align_of::<TeplSelectionType>()}),
    ("TeplTab", Layout {size: size_of::<TeplTab>(), alignment: align_of::<TeplTab>()}),
    ("TeplTabGroupInterface", Layout {size: size_of::<TeplTabGroupInterface>(), alignment: align_of::<TeplTabGroupInterface>()}),
    ("TeplTabLabel", Layout {size: size_of::<TeplTabLabel>(), alignment: align_of::<TeplTabLabel>()}),
    ("TeplView", Layout {size: size_of::<TeplView>(), alignment: align_of::<TeplView>()}),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("TEPL_COMPRESSION_TYPE_GZIP", "1"),
    ("TEPL_COMPRESSION_TYPE_NONE", "0"),
    ("TEPL_FILE_LOADER_ERROR_ENCODING_AUTO_DETECTION_FAILED", "1"),
    ("TEPL_FILE_LOADER_ERROR_TOO_BIG", "0"),
    ("TEPL_FILE_SAVER_ERROR_EXTERNALLY_MODIFIED", "1"),
    ("TEPL_FILE_SAVER_ERROR_INVALID_CHARS", "0"),
    ("TEPL_FILE_SAVER_FLAGS_CREATE_BACKUP", "4"),
    ("TEPL_FILE_SAVER_FLAGS_IGNORE_INVALID_CHARS", "1"),
    ("TEPL_FILE_SAVER_FLAGS_IGNORE_MODIFICATION_TIME", "2"),
    ("TEPL_FILE_SAVER_FLAGS_NONE", "0"),
    ("TEPL_GUTTER_RENDERER_FOLDS_STATE_CONTINUE", "4"),
    ("TEPL_GUTTER_RENDERER_FOLDS_STATE_END", "8"),
    ("TEPL_GUTTER_RENDERER_FOLDS_STATE_NONE", "0"),
    ("TEPL_GUTTER_RENDERER_FOLDS_STATE_START_FOLDED", "1"),
    ("TEPL_GUTTER_RENDERER_FOLDS_STATE_START_OPENED", "2"),
    ("TEPL_NEWLINE_TYPE_CR", "1"),
    ("TEPL_NEWLINE_TYPE_CR_LF", "2"),
    ("TEPL_NEWLINE_TYPE_LF", "0"),
    ("TEPL_SELECTION_TYPE_MULTIPLE_LINES", "2"),
    ("TEPL_SELECTION_TYPE_NO_SELECTION", "0"),
    ("TEPL_SELECTION_TYPE_ON_SAME_LINE", "1"),
];


