// This file was generated by gir (https://github.com/gtk-rs/gir @ 7f5a2b5)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT

#[cfg(any(feature = "v2_0", feature = "dox"))]
mod action_info_central_store;
#[cfg(any(feature = "v2_0", feature = "dox"))]
pub use self::action_info_central_store::ActionInfoCentralStore;
#[cfg(any(feature = "v2_0", feature = "dox"))]
pub use self::action_info_central_store::ActionInfoCentralStoreExt;

#[cfg(any(feature = "v2_0", feature = "dox"))]
mod action_info_store;
#[cfg(any(feature = "v2_0", feature = "dox"))]
pub use self::action_info_store::ActionInfoStore;
#[cfg(any(feature = "v2_0", feature = "dox"))]
pub use self::action_info_store::ActionInfoStoreExt;

mod application_window;
pub use self::application_window::ApplicationWindow;
pub use self::application_window::ApplicationWindowExt;

#[cfg(any(feature = "v3_0", feature = "dox"))]
mod factory;
#[cfg(any(feature = "v3_0", feature = "dox"))]
pub use self::factory::Factory;
#[cfg(any(feature = "v3_0", feature = "dox"))]
pub use self::factory::FactoryExt;

mod menu_shell;
pub use self::menu_shell::MenuShell;
pub use self::menu_shell::MenuShellExt;

#[cfg(any(feature = "v2_0", feature = "dox"))]
mod action_info;
#[cfg(any(feature = "v2_0", feature = "dox"))]
pub use self::action_info::ActionInfo;

#[doc(hidden)]
pub mod traits {
    #[cfg(any(feature = "v2_0", feature = "dox"))]
    pub use super::ActionInfoCentralStoreExt;
    #[cfg(any(feature = "v2_0", feature = "dox"))]
    pub use super::ActionInfoStoreExt;
    pub use super::ApplicationWindowExt;
    #[cfg(any(feature = "v3_0", feature = "dox"))]
    pub use super::FactoryExt;
    pub use super::MenuShellExt;
}
